---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: coredns
  name: dns
  namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: coredns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: coredns
    spec:
      containers:
        - name: dns
          args:
            - -conf
            - /etc/coredns/Corefile
            - -p
            - "5555"
          image: coredns/coredns:1.12.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 5555
              name: dns
              protocol: UDP
            - containerPort: 5555
              name: dns-tcp
              protocol: TCP
            - containerPort: 9153
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 70Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
              readOnly: true
            - name: dns-zones
              mountPath: /etc/coredns/zones
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: corefile
            defaultMode: 420
            items:
              - key: Corefile
                path: Corefile
        - name: dns-zones
          configMap:
            name: dns-zones
            defaultMode: 420
