---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: coredns
  namespace: metallb
spec:
  addresses:
    - 192.168.6.7/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dns-advert
  namespace: metallb
spec:
  ipAddressPools:
    - coredns