---
global:
  namespace: vault
  tlsDisble: false
injector:
  enabled: true
  image:
    repository: "hashicorp/vault-k8s"
    tag: "1.6.2"
  agentImage:
    repository: "hashicorp/vault"
    tag: "1.19.0"
server:
  enabled: true
  image:
    repository: "hashicorp/vault"
    tag: "1.19.0"
  dev:
    enabled: false
  ingress:
    enabled: false
  auditStorage:
    enabled: true
  service:
    enabled: true
    type: NodePort
    nodePort: 32001
    activeNodePort: 32002
    standbyNodePort: 32003
  standalone:
    enabled: true
    config: |
      ui = true
      cluster_name = "gadgieops-vault"
      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-ha-tls/tls.crt"
        tls_key_file  = "/vault/userconfig/vault-ha-tls/tls.key"
        tls_client_ca_file = "/vault/userconfig/vault-ha-tls/crt.ca"
        }
      storage "file" {
        path = "/vault/data"
      }
  ha:
    enabled: false
    replicas: 3
    raft:
      enabled: true
      config: |
        ui = true
        cluster_name = "gadgieops-vault"
        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-ha-tls/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-ha-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-ha-tls/crt.ca"
        }
        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
          }
        }
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-ha-tls/ca.crt
    VAULT_TLSCERT: /vault/userconfig/vault-ha-tls/tls.crt
    VAULT_TLSKEY: /vault/userconfig/vault-ha-tls/tls.key
    VAULT_ADDR: https://127.0.0.1:8200
  volumes:
    - name: userconfig-vault-ha-tls
      secret:
        defaultMode: 420
        # secretName: vault-ha-tls
        secretName: vault-gadgieops-yem-tls
  volumeMounts:
    - mountPath: /vault/userconfig/vault-ha-tls
      name: userconfig-vault-ha-tls
      readOnly: true
ui:
  enabled: true
  activeVaultPodOnly: false
  serviceType: NodePort
  serviceNodePort: 32000
