---

  ###
  # kube-apiserver

- name: Allow  direct kube-apiserver access IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ kube_api_port }}"
    src: "{{ item }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-apiserver IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw

- name: Allow direct kube-apiserver access OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ kube_api_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-apiserver OUT"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw

- name: Allow vip kube-apiserver access IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ haproxy_port }}"
    src: "{{ item }}"
    dest: "{{ vip }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-apiserver vip IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw

- name: Allow vip kube-apiserver access OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ haproxy_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ vip }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-apiserver vip OUT"
  tags: firewall, ufw

  ###
  # etcd

  # client

- name: Allow etcd client/peer traffic IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ etcd_client_port }}:{{ etcd_peer_port }}"
    src: "{{ item }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "etcd client/peer IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw

- name: Allow etcd client/peer traffic OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ etcd_client_port }}:{{ etcd_peer_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "etcd client/peer OUT"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw

- name: Allow hashicorp vault UI traffic IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ vault_ui_port }}"
    src: "{{ secure_zone }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "hashicorp vault UI IN"
  when: vault | default(false) | bool
  tags: firewall, ufw

- name: Allow DNS traffic IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ dns_port }}"
    src: "{{ secure_zone }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "DNS IN"
  tags: firewall, ufw