---

  ###
  # kube-apiserver

- name: Allow kube-apiserver server IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ kube_api_port }}"
    src: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-apiserver IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw

- name: Allow kube-apiserver OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ kube_api_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-apiserver OUT"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw

  ###
  # etcd

  # client

- name: Allow etcd client/peer traffic IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ etcd_client_port }}:{{ etcd_peer_port }}"
    src: "{{ item }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "etcd client/peer IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw

- name: Allow etcd client/peer traffic OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ etcd_client_port }}:{{ etcd_peer_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "etcd client/peer OUT"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
  tags: firewall, ufw