# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-issuer
  namespace: gitlab
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['gitlab-issuer']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-issuer
  namespace: gitlab
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-issuer