apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-gadgieops-yem
  namespace: test
spec:

  secretName: test-gadgieops-yem-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  subject:
    organizations:
      - gadgieops

  commonName: test.gadgieops.yem

  dnsNames:
    - test.gadgieops.yem
  # emailAddresses:
  #   - gadge@gadgieops.yem
  ipAddresses:
    - 192.168.6.3
    - 192.168.6.4
    - 192.168.6.5

  issuerRef:
    name: test-issuer
    kind: Issuer
