apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: test
spec:
  vault:
    server: https://vault.vault:8200
    path: pki/sign/gadgieops.yem
    caBundleSecretRef:
      key: vault.ca
      name: vault-ha-tls
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: issuer-token
          key: token