---
- name: Install containerd
  ansible.builtin.include_role:
    name: geerlingguy.containerd
    apply:
      tags: containerd, cri
  tags: containerd, cri

###
# Enable CRI plugin and set cgroup driver to systemd as per:
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
#

- name: Remove cri from disabled plugins list
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    state: absent
    line: disabled_plugins = ["cri"]
  tags: containerd

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
  tags: containerd