---
- name: Allow public kube-apiserver access IN
  community.general.ufw:
    rule: allow
    port: "{{ haproxy_port }}"
    src: "{{ secure_zone }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 210
    comment: "public kube-apiserver IN"
  tags: firewall, ufw, haproxy

- name: Deploy HAProxy
  ansible.builtin.include_role:
    name: robertdebock.haproxy
    apply:
      tags: haproxy
  vars:
    haproxy_frontends:
      - name: k8s-api
        address: "{{ ansible_host}}"
        port: "{{ haproxy_port }}"
        default_backend: k8s-api
        mode: tcp
        option: tcplog
    haproxy_backend_default_balance: roundrobin
    haproxy_backends:
      - name: k8s-api
        mode: tcp
        httpcheck: false
        option: tcplog
        servers:
          - name: k8s-staging-01
            address: "{{ hostvars['k8s_staging_01']['ansible_host'] }}"
          - name: k8s-staging-02
            address: "{{ hostvars['k8s_staging_02']['ansible_host'] }}"
          - name: k8s-staging-03
            address: "{{ hostvars['k8s_staging_03']['ansible_host'] }}"
        port: "{{ kube_api_port}}"
        options:
          - check
          - check-ssl
          - "verify none"
  tags: haproxy
