---
- name: Include shared firewall rules
  ansible.builtin.include_tasks:
    file: shared-k8s-tasks/firewall.yml
    apply:
      tags: firewall, ufw
  tags: firewall, ufw

  ###
  # kubelet

- name: Allow kubelet traffic IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ kubelet_port }}"
    src: "{{ item }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kubelet IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"

- name: Allow kubelet API OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ kubelet_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kubelet OUT"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"

  ###
  # kube-scheduler

- name: Allow kube-scheduler traffic IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ kube_scheduler_port }}"
    src: "{{ item }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-scheduler IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"

- name: Allow kube-scheduler traffic OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ kube_scheduler_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-scheduler OUT"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"

  ###
  # kube-controller

- name: Allow kube-controller traffic IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ kube_controller_port }}"
    src: "{{ item }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-controller IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"

- name: Allow kube-controller traffic OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ kube_controller_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "kube-controller OUT"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"

  ###
  # Calico Networking

- name: Allow BGP for Calico Networking IN
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ calico_bgp_port }}"
    src: "{{ item }}"
    dest: "{{ ansible_host }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "Calico BGP IN"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"

- name: Allow BGP for Calico Networking OUT
  community.general.ufw:
    rule: allow
    direction: out
    port: "{{ calico_bgp_port }}"
    src: "{{ ansible_host }}"
    dest: "{{ item }}"
    proto: tcp
    state: enabled
    insert: 0
    insert_relative_to: first-ipv4
    comment: "Calico BGP OUT"
  loop: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('string') | list | reject('search', ansible_host) }}"
