---
- name: Deploy Highly Available k8s Cluster
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Setup initial FW Rules
      ansible.builtin.include_tasks:
        file: ha-k8s-tasks/gp-firewall.yml
        apply:
          tags: firewall, ufw
      when:
        - set_gp_fw | default(false) | bool
        - setup_ufw | default(false) | bool
      tags: firewall, ufw

    - name: Includes keepalived tasks
      ansible.builtin.include_tasks:
        file: ha-k8s-tasks/keepalived.yml
        apply:
          tags: vrrp
      tags: vrrp

    - name: Includes haproxy tasks
      ansible.builtin.include_tasks:
        file: shared-k8s-tasks/haproxy.yml
        apply:
          tags: haproxy
      tags: haproxy

    - name: Wait for API Reachability
      ansible.builtin.wait_for:
        host: "{{ vip }}"
        port: "{{ haproxy_port }}"
        delay: 2
      tags: haproxy, wait

    - name: Install Containerd
      ansible.builtin.include_tasks:
        file: ha-k8s-tasks/containderd.yml
        apply:
          tags: containerd, cri
      tags: containerd, cri

    - name: Prepre server for Kubernetes
      ansible.builtin.include_tasks:
        file: ha-k8s-tasks/k8s-prep.yml
        apply:
          tags: k8s
      tags: k8s

    - name: Configure UFW for Kubernetes Ports
      ansible.builtin.include_tasks:
        file: shared-k8s-tasks/k8s-firewall.yml
        apply:
          tags: firewall, ufw
      when:
        - setup_ufw | default(false) | bool
      tags: firewall, ufw

    - name: Install Kubernetes
      ansible.builtin.include_tasks:
        file: ha-k8s-tasks/k8s-install.yml
        apply:
          tags: k8s
      tags: k8s
