---
- name: Deploy k3s
  hosts: k3s_servers
  gather_facts: true
  become: true
  pre_tasks:

    - name: Set node lists
      ansible.builtin.include_tasks:
        file: ha-k3s-tasks/set-node-lists.yml
        apply:
          tags: always
      tags:
        - always

    - name: Setup k3s firewall rules
      ansible.builtin.include_tasks:
        file: ha-k3s-tasks/fw.yml
        apply:
          tags: ufw
      when:
        - setup_ufw | default(true) | bool
      tags:
        - ufw
        - ufw-global
        - ufw-k3s
        - ufw-opt

    - name: Include DNS tasks
      ansible.builtin.include_tasks:
        file: ha-k3s-tasks/dns.yml
        apply:
          tags: dns
      when: dns | default(false) | bool
      tags:
        - dns
        - ufw

    - name: Include keepalived tasks
      ansible.builtin.include_tasks:
        file: ha-k3s-tasks/keepalived.yml
      tags:
        - vrrp
        - ufw

    - name: Include HAProxy tasks
      ansible.builtin.include_tasks:
        file: ha-k3s-tasks/haproxy.yml
      tags:
        - haproxy
        - ufw

    - name: Test VRRP/HA Endpoint Reachability
      ansible.builtin.wait_for:
        host: "{{ vip }}"
        port: "{{ haproxy_port }}"
        delay: 2

  roles:

    - role: k3s.orchestration.prereq
      tags:
        - k3s
        - prereq

    - role: k3s.orchestration.airgap
      tags:
        - k3s
        - airgap

    - role: k3s.orchestration.k3s_server
      tags:
        - k3s
        - server

    - role: k3s.orchestration.k3s_agent
      when: agents is defined
      tags:
        - k3s
        - agent

  tasks:

    - name: Include k3s config tasks
      ansible.builtin.include_tasks:
        file: ha-k3s-tasks/config.yml
        apply:
          tags: kubeconfig
      tags:
        - kubeconfig
