---
- name: Deploy Highly Available k8s Cluster
  hosts: all
  become: true
  gather_facts: true
  tasks:
    
    - name: Includes keepalived tasks
      ansible.builtin.include_tasks:
        file: ha-k8s-tasks/keepalived.yml
        apply:
          tags: vrrp
      tags: vrrp

    - name: Includes haproxy tasks
      ansible.builtin.include_tasks:
        file: ha-k8s-tasks/haproxy.yml
        apply:
          tags: haproxy
      tags: haproxy

    - name: Wait for API Reachability
      ansible.builtin.wait_for:
        host: "{{ vip }}"
        port: 443
        delay: 2
      tags: haproxy, wait

    - name: Install containerd
      ansible.builtin.include_role:
        name: geerlingguy.containerd
        apply:
           tags: containerd
      tags: containerd

    - name: Install Kubernetes
      ansible.builtin.include_tasks:
        file: ha-k8s-tasks/kubernetes.yml
        apply:
          tags: k8s
      tags: k8s