---
- name: Harden Ubuntu 24.04 to CIS Benchmark
  hosts: all
  become: true
  gather_facts: true

  vars:
    audit_dir: "{{playbook_dir}}/../../audits/{{ inventory_hostname }}/"

  tasks:

    - name: Ensure audit directory exists
      ansible.builtin.file:
        path: "{{ audit_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: false

    - name: Write all ansible facts to audit directory per inventory host
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "{{ audit_dir }}ansible-facts.json"
        mode: '0644'
      delegate_to: localhost
      become: false

    - name: Audit & Enforce Complicance to Ubuntu 24.04 to CIS Benchmark
      ansible.builtin.include_role:
        name: lockdown_u24-cis
      vars:
        setup_audit: "{{ audit | default(true) }}"
        run_audit: "{{ audit | default(true) }}"
        audit_only: "{{ auditonly | default(false) }}"
        fetch_audit_output: "{{ audit | default(true) }}"
        audit_output_destination: "{{ audit_dir }}"
