apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vault-so
  name: gl-pg-user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gl-pg-user-sa
  namespace: gitlab
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: gl-pg-user-secret
  namespace: gitlab
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: gl-pg-user
    serviceAccount: gl-pg-user-sa
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-gl-pg-user
  namespace: gitlab
spec:
  type: kv-v2
  mount: kvv2
  path: gl-pg-user/config
  destination:
    name: gl-pg-user-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: gl-pg-user-secret
