# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.4.3"

Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-24.04"

    (1..3).each do |i|
        config.vm.define "k8s-staging-0#{i}" do |vm_config|

            vm_config.vm.hostname = "k8s-staging-0#{i}"

            vm_config.vm.network "private_network",ip: "192.168.6.#{i + 1}", netmask: "255.255.255.224", gateway: "192.168.6.1"
            
            vm_config.vm.provider "vmware_desktop" do |vm|

                vm.gui = true
                vm.linked_clone = false
                vm.memory = "4096"
                vm.cpus = 2
                vm.vmx["sata0:1.deviceType"] = "cdrom-image"
                vm.vmx["sata0:1.filename"] = "#{Dir.pwd}/seeds/cloud-init.iso"
                vm.vmx["sata0:1.startConnected"] = "TRUE"
                vm.vmx["sata0:1.allowGuestConnectionControl"] = "TRUE"

            end
        end
    end
end
