
Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-24.04"

    (1..3).each do |i|
        config.vm.define "k8s-staging-#{i}" do |vm_config|

            vm_config.vm.hostname = "k8s-staging-#{i}"

            vm_config.vm.network "private_network",ip: "192.168.6.#{i + 1}", netmask: "255.255.255.224", gateway: "192.168.6.1"
            vm_config.vm.disk :disk, size: "96GB", name: "k8sstaging#{i}", primary: true

            # vm.count_init not supported by vmware_desktop
            # https://github.com/hashicorp/vagrant-vmware-desktop/issues/130
            # vm_config.vm.cloud_init :user_data do |cloud_init|
            #     cloud_init.content_type = "text/cloud-config"
            #     cloud_init.path = "./config.cfg"
            # end
            
            vm_config.vm.provider "vmware_desktop" do |vm|

                vm.gui = false
                vm.linked_clone = false
                vm.memory = "4096"
                vm.cpus = 2
            end
        end
    end
end
