apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-gadgieops-yem
  namespace: vault
spec:

  secretName: vault-gadgieops-yem-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - gadgieops

  commonName: vault.gadgieops.yem

  dnsNames:
    - vault.gadgieops.yem
  # emailAddresses:
  #   - gadge@gadgieops.yem
  ipAddresses:
    - 192.168.6.3
    - 192.168.6.4
    - 192.168.6.5

  issuerRef:
    name: vault-issuer
    kind: Issuer
