apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-gadgieops-yem
  namespace: vault
spec:

  secretName: vault-gadgieops-yem-tls

  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  subject:
    organizations:
      - gadgieops

  commonName: vault.gadgieops.yem

  dnsNames:
    - "vault.gadgieops.yem"
    - "vault.vault"
    - "vault.vault-internal"

  ipAddresses:
    - 192.168.6.3
    - 192.168.6.4
    - 192.168.6.5
    - 127.0.0.1

  issuerRef:
    name: vault-issuer
    kind: Issuer
