apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`vault.gadgieops.yem`)
    services:
    - name: vault
      port: 8200
  tls:
    secretName: vault-gadgieops-yem-tls
    passthrough: true