---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: vault
spec:
  vault:
    path: pki_int/sign/gadgieops.yem
    server: https://vault.vault:8200
    caBundleSecretRef:
      key: vault.ca
      name: vault-ha-tls
    auth:
      kubernetes:
        role: vault-issuer
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer