---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: vault
spec:
  vault:
    path: pki_int/sign/gadgieops.yem
    server: https://vault.gadgieops.yem:32001
    caBundleSecretRef:
      key: ca.crt
      name: vault-gadgieops-yem-tls
    auth:
      kubernetes:
        role: vault-issuer
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer