roles:
# Latest tested commit on devel branch 21.04.2025
# Release 1.0.1 didn't have code to fetch pre/post audit files
# Should fix this requirement to the next release when available
- name: lockdown_u24-cis
  src: https://github.com/ansible-lockdown/UBUNTU24-CIS.git
  version: "f90b698"