collections:
  - name: k3s.orchestration
    source: https://github.com/k3s-io/k3s-ansible.git
    version: "1.0.0"
    type: git

roles:
# Latest tested commit on devel branch 21.04.2025
# Release 1.0.1 didn't have code to fetch pre/post audit files
# Should fix this requirement to the next release when available
- name: lockdown_u24-cis
  src: https://github.com/ansible-lockdown/UBUNTU24-CIS.git
  version: "f90b698"
  # Jeff hasn't released in years but PR are still getting merged
  # Pinned to latest commit on master branch 21.04.2025
- name: geerlingguy.containerd
  src: https://github.com/geerlingguy/ansible-role-containerd.git
  version: "4246310"
- name: geerlingguy.kubernetes
  src: https://github.com/geerlingguy/ansible-role-kubernetes.git
  version: 2b2efa7
- name: evrardjp.keepalived
  version: "8.2.0"
- name: robertdebock.haproxy
  version: "4.8.0"